### ISSUE TITLE
When I switch to the next picture, scaleStateListener does not execute

### ISSUE THREAD

**Issue by LebenNNA** [renancaraujo/photo_view#100]
When I switch to the next picture, scaleStateListener does not execute

**Comment by renancaraujo** [comment]
Does that happen on Gallery?

**Comment by LebenNNA** [comment]
Yes，In the past version, switch from picture 1 to picture 2. If picture 1 is zooming, switching to picture 2 will trigger scaleStateListener, but the current version will not trigger.

**Comment by renancaraujo** [comment]
@LebenNNA Opinions ahead: That is, as I see, an expected behavior. Since `scaleState` is a state referring particularly to one image in the gallery, I don't think an image change is a change on this state. If it helps, there is anotehr callback you can use to detect when a image is swipped in or out in the gallery: [onPageChanged](https://pub.dartlang.org/documentation/photo_view/latest/photo_view_gallery/PhotoViewGallery/onPageChanged.html)

**Comment by renancaraujo** [comment]
I'm closing this issue for now. If you think your question has not been solved or do not agree with the outcome, please, feel free to reopen it.
