### ISSUE TITLE
Add Actions button

### ISSUE THREAD

**Issue by radvansky-tomas** [renancaraujo/photo_view#102]
What I really miss here is classic actions button, which opens viewed image in 3rd party apps, or give users list of actions he can do with it. (like copy, print etc)

![image](https://user-images.githubusercontent.com/12473664/53072442-fe7cfe80-3549-11e9-92aa-2dca541edf74.png)

**Comment by renancaraujo** [comment]
PhotoView is a minimalistic widget concerned only with task that is to show a zoomable content. Features like this one, besides being useful in the context of your app, can not be in others (for instance, I have an app that shows a editing photo on a zoomable context).

PhotoView can be combined to any layout feature on you app, within a stack you can put any button alongside the zoomable content.

Since it seems not to be a PhotoView issue, im closing this one. If you feel that you weren't understood right, please feel free to reopen this issue explaining what you mean. Thanks
