### ISSUE TITLE
[BUG] Hero-animation doesn't play for network imagae at the first time since hot restart

### ISSUE THREAD

**Issue by alexandr2levin** [renancaraujo/photo_view#128]
Hello!
I try to use NetworkImage as a provider for the PhotoView, and it breaks our Hero animation.

**What is the current behavior?**
Hero animation plays only on the second attempt. On the first one Hero animation is ignored.

Probably, this is happening because of loadingChild which is shown before the image is loaded. It will be nice to let us use the PhotoViewImageWrapper to provide our own child and to manage an image's loading state with such packages like cached_network_image.

**How to fix**
I found a tmp workaround to preload the image before the animation began.
```

import 'dart:async';

import 'package:breeder/domain/middleware/epics/uri.dart';
import 'package:cached_network_image/cached_network_image.dart';
import 'package:flutter/material.dart';

Future<void> preloadImages(List<String> imagesIds) async {
  for(var imageId in imagesIds) {
    var provider = CachedNetworkImageProvider(
      attachmentUrl.toString() + '/' + imageId,
    );
    await _getImage(provider);
  }
}

Future<ImageInfo> _getImage(ImageProvider imageProvider) {
  final Completer completer = Completer<ImageInfo>();
  final ImageStream stream =
  imageProvider.resolve(const ImageConfiguration());
  final listener = (ImageInfo info, bool synchronousCall) {
    if (!completer.isCompleted) {
      completer.complete(info);
    }
  };
  stream.addListener(listener);
  completer.future.then((_) {
    stream.removeListener(listener);
  });
  return completer.future;
}
```

**Comment by renancaraujo** [comment]
As the docs say:

> When heroTag is specified, the image provider retrieval process should be sync.

When first built, PhotoView has to choose between painting the image right away or wait until it resolves. Since the zooming constraints are highly dependent on the size of the image, the priority is to always wait until the image is loaded completely, rendering `loadingChild` in the meantime.  That is, except when `heroTag` is provided. In this case, the image has to be painted in the first frame, that is the only way that Flutter can perform the `hero` animation. 

I would keep prefetching the image in order to have it ready before the animation starts.

**Comment by renancaraujo** [comment]
Since there is no update on this, I will close this issue for now. If you consider your question not solved, feel free to reopen it and let's move forward with the discussion.
