### ISSUE TITLE
When sliding the PageView, the image flashes

### ISSUE THREAD

**Issue by nekocode** [renancaraujo/photo_view#181]
I use the `PhotoViewGallery` in my project and only want to enable the hero animation of the selected item, so I wrote the following code:

```dart
PhotoViewGalleryPageOptions _buildItem(BuildContext context, int index) {
  return PhotoViewGalleryPageOptions(
    // ...
    heroAttributes: selectedIndex == index
        ? PhotoViewHeroAttributes(tag: item.heroTag)
        : null,
  );
}
```

But see the following gif, these code will cause image flash when sliding the PageView:

<img src="https://user-images.githubusercontent.com/4783781/64917821-52418480-d7c7-11e9-9a28-855b4c629da9.gif" width="200">

So I try to check the source code to find the reason. And I find that this library controls the loading animation by itself, rather than using the `loadingBuilder` option providing by the Image widget. It uses a `FutureBuilder` to conditionally build an image or loading widget:

```dart
Widget _buildImage(BuildContext context, BoxConstraints constraints) {
  return widget.heroAttributes == null
      ? _buildAsync(context, constraints)
      : _buildSync(context, constraints);
}

Widget _buildAsync(BuildContext context, BoxConstraints constraints) {
  return FutureBuilder(
      future: _getImage(),
      builder: (BuildContext context, AsyncSnapshot<ImageInfo> info) {
        if (info.hasData) {
          return _buildWrapperImage(context, constraints);
        } else {
          return _buildLoading();
        }
      });
}
```

When set the `heroAttributes` option to null, the `_buildImage()` will return a `FutureBuilder` which will always return the `_buildLoading()` in the first frame. And if the image is cached before, the `FutureBuilder` will return the `_buildWrapperImage()` immediately in next frame. Finally it will cause the flash.

I don't think using `FutureBuilder` here is good. And why not just use the `loadingBuilder` of the Image widget to show the loading animation? Its implementation is more robust.

**Comment by graknol** [comment]
Isn't the problem here that the future is being recreated on every build, which then causes the flash?
According to Flutter guidelines, you should create the future once, for instance in initState.

**Comment by renancaraujo** [comment]
> why not just use the `loadingBuilder`

Some reasons:
1- Because we dont want the user zooming on a circular progress indicator. 
2- Because we need the dimensions of the image to perform initial scalings and since we receive providers.

> I don't think using FutureBuilder here is good. 

PRs are always welcome. Even more the non breaking stuff ones. 



That said, you can: 
1- Remove the condition to pass the hero attributes. I dont see the need for momiting hero attributes, since the non selecetd ones wont be rendered anyway. heck the gallery on teh example app.
2- You can create a gallery with a `PageView.custom` and a keepalive as shown [here](https://api.flutter.dev/flutter/widgets/PageView/PageView.custom.html). Since pageview has not such a thing as `addAutomaticKeepAlives`. That wouldn't rebuild each PhotoView on every page change.
