### ISSUE TITLE
[BUG]Gallery can't change page smoothly 

### ISSUE THREAD

**Issue by criswonder** [renancaraujo/photo_view#212]
![out1](https://user-images.githubusercontent.com/1430134/69215038-88bec580-0ba3-11ea-8e34-46d31e2f2e93.gif)

Flutter Version:
Flutter 1.9.1+hotfix.6 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 68587a0916 (10 weeks ago) • 2019-09-13 19:46:58 -0700
Engine • revision b863200c37
Tools • Dart 2.5.0

Test Devices:
1. phone model is MI6/Android  9

2. Google Pixel2/ Android 9

code: 
master branch

Thank you!

**Comment by hugocbpassos** [comment]
I also tested in some other devices (same Flutter version as described in the issue):

* Mi A2, Android 9: Works perfectly.
* LG G7 ThinQ, Android 8: Hard to change the pages.
* Pocophone F1, Android 8: Really hard to change the pages.

@criswonder states [here](https://github.com/renancaraujo/photo_view/pull/197#issuecomment-555863108) that this happens when the page is zoomed in, but for me it doesn't make any difference.

**Comment by diegogarciar** [comment]
Issue is also present on iOS, I tested it with iPhone 11 Pro Max

**Comment by dingzuhua** [comment]
photo_view: 0.4.2 is available on android

**Comment by coffegen** [comment]
same as for me.
device is galaxy a50
photoview version 0.9.0

**Comment by renancaraujo** [comment]
Ok, looks like a widespread bug among users, but I was not successful to reproduce it in any of my devices (Redmi Note 7 and iPhone 7). Once I get some time I will look into it.
