### ISSUE TITLE
Pull up/down to close?

### ISSUE THREAD

**Issue by Lucavon** [renancaraujo/photo_view#5]
This is a great widget, thanks for creating and uploading it!
I have a suggestion: In many apps, you can close PhotoView equivalents by pulling them up or down with one finger (example: [https://www.youtube.com/watch?v=kzIcnYfznxI](video)).
Maybe we could supply a function that is executed when the picture is pulled up/down and then "dropped"?

Once again, super useful widget!

**Comment by renancaraujo** [comment]
That is a coo idea, but we have two problems there:
- Since one of the core features of photo_view is  screen edge limitation, the image is oriented to be centralized on the screen as much as possible
- The gesture you are referring to, is dealed via `VerticalGestureRecognizer` which is different than what we use to identify scale`ScaleGestureRecognizer`. I'm not sure how the two of them would fight in the [gesture arena](https://flutter.io/gestures/) if we inserted

I think this behaviour could be handled by another widget that contains photo_view, since we may have even an route change depending the outcome of the user's gesture.

**Comment by Lucavon** [comment]
Thanks for the reply! I'll try using a widget containing a PhotoView as you suggested tomorrow, if it works, I'll post the code!

**Comment by renancaraujo** [comment]
The example project in this repo would be a good place to test this behavior. Pull requests are welcome

**Comment by StefanLobbenmeier** [comment]
Not sure why this has been closed without a snippet being posted, but here is what I used:

```
@override
  Widget build(BuildContext context) {
    return GestureDetector(
      onVerticalDragUpdate: (dragUpdateDetails) {
        Navigator.of(context).pop();
      },
      behavior: HitTestBehavior.translucent,
      child: PhotoView(
      // up to you

      ),
    );
```

It works ok-ish, you have to drag about 20 pixels and then it closes. Still not as pretty as for example the transition in the Apollo reddit app (which I consider ideal), but at least you can close it without the back button.
