### ISSUE TITLE
Gallery - zoom out result in can't silde

### ISSUE THREAD

**Issue by hupo376787** [renancaraujo/photo_view#61]
Suppose have 3 images, when zoom out the first image, smaller than the screen size.

Then I can't slide to the new image. 

I tried to set each image's minScale, it's double. And each image's size are different. I can't use BoxFit.fill.

How to do that.

**Comment by renancaraujo** [comment]
That happens because of the "locking" behavior in the gallery. When the internal state of the current photoview's page of the gallery is `zooming`, we lock the pageview to changes. That was implemented to avoid confusion between the panning gesture of a zoomed image and the swipe gesture in PageView. That confusion only happens when the image's dimensions are larger than the screen. We are locking in all cases, regardless of the current image dimension. That is a bug. 

Since I'm having trouble to find a time to work on PhotoView, a PR in this regard would be of a great help.

**Comment by renancaraujo** [comment]
After #76 this should be solved
